### ISSUE TITLE
Mildred - Create ingestion pipeline for Zenodo data

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/use-cases#2]

**Comment by jkesanie** [comment]
Created, tested and exported two pipelines. One that searches for everything containing the term "helsinki" and stores the results in RDF format to graph titled "zenode-uh-related". The other one harvests data using OAI-PMH interface from the hulib community and adds the new data to the graph "zenodo-uh-communities".

**Comment by blankdots** [comment]
@jkesanie would it be beneficial to have a Git repository with these pipelines ? ... like we have with the plugins.
